// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 computer-optimized.glb -T 
// Files: computer-optimized.glb [486.38KB] > E:\myPortfolio\Portfolio\public\models\computer-optimized-transformed.glb [39.72KB] (92%)
// */

// import React from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Computer(props) {
//   const { nodes, materials } = useGLTF('/models/computer-optimized-transformed.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group position={[-4.005, 67.549, 58.539]}>
//         <mesh castShadow receiveShadow geometry={nodes.Cube000_ComputerDesk_0001_1.geometry} material={materials['ComputerDesk.001']} />
//         <mesh castShadow receiveShadow geometry={nodes.Cube000_ComputerDesk_0001_2.geometry} material={materials['FloppyDisk.001']} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/computer-optimized-transformed.glb')


import React from "react";
import { useGLTF } from "@react-three/drei";

export function Computer(props) {
  const { nodes, materials } = useGLTF(
    "models/computer-optimized-transformed.glb"
  );

  // ✅ SAFETY CHECK (prevents blank screen)
  if (!nodes || !materials) {
    console.error("GLTF nodes or materials missing");
    return null;
  }

  const desk1 = nodes?.Cube000_ComputerDesk_0001_1;
  const desk2 = nodes?.Cube000_ComputerDesk_0001_2;

  // ✅ If node names mismatch → fail gracefully
  if (!desk1 || !desk2) {
    console.error("Expected GLTF nodes not found:", nodes);
    return null;
  }

  return (
    <group {...props} dispose={null}>
      <group position={[-4.005, 67.549, 58.539]}>
        <mesh
          castShadow
          receiveShadow
          geometry={desk1.geometry}
          material={materials["ComputerDesk.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={desk2.geometry}
          material={materials["FloppyDisk.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/computer-optimized-transformed.glb");
